
keepers = ['Sleep', 'Money', 'Time', 'Music', 'Sun', 'Toaster', 'Eye', 'Brain', 'Moon',
           'Love', 'Peace', 'Rocket', 'Television', 'Milk', 'Cookies', 'Chocolate', 'Dreams', 'Party', 'Bread']

goals ={'Milk & Cookies': ('Milk', 'Cookies'),
        'Party Snacks': ('Party', '@anyfood'),
        'Night & Day': ('Sun', 'Moon'),
        'Turn Up Volume': ('Music', 'Party'),
        'Great Theme Song': ('Music', 'Television'),
        'Winning Lottery': ('Dreams', 'Money'),
        'Toast': ('Bread', 'Toaster'),
        'Eye of Beholder': ('Eye', 'Love'),
        'Dreamland': ('Sleep', 'Dreams'),
        'Squishy Chocolate': ('Sun', 'Chocolate'),
        'Chocolate Cookies': ('Chocolate', 'Cookies'),
        'Rocket to Moon': ('Rocket', 'Moon'),
        'World Peace': ('Dreams', 'Peace'),
        'Chocolate Milk': ('Chocolate', 'Milk'),
        'Rocket Science': ('Rocket', 'Brain'),
        'Time is Money': ('Time', 'Money'),
        'Bread & Chocolate': ('Bread', 'Chocolate'),
        'Party Time': ('Party', 'Time'),
        'Five Keepers': ('@fivekeepers'),
        'The Brain (No TV)': ('Brain', '@notv'),
        'Ten Cards in Hand': ('@tencards'),
        'Bed Time': ('Sleep', 'Time'),
        'Cant Buy Me Love': ('Money', 'Love'),
        'Hearts & Minds': ('Love', 'Brain'),
        'Baked Goods': ('Bread', 'Cookies'),
        'The Minds Eye': ('Eye', 'Brain'),
        'The Appliances': ('Toaster', 'Television'),
        'Day Dreams': ('Dreams', 'Sun'),
        'Hippyism': ('Peace', 'Love'),
        'Lullaby': ('Sleep', 'Music')
        }